baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"

themesDir = "themes"
theme = "hugo-whisper-theme"

title = "WOM Platform Documentation"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Guide"
    url = "/guide/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/guide/'
  homepage_button_text = 'To the User Guide'
  homepage_intro = 'WOM is an open general-purpose rewarding platform based on an exchange system of anonymous vouchers.'
  #homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/wom-logo.png"
      standard  = "/images/wom-logo.png"
